host:
  hostname: "localhost"
  user: "vscode"
  log_directory: "/tmp"
  workdir: "/tmp"
  submit_arguments:
    defaults:
      queue: nf
      memory_per_cpu: 8Gb
      job_name: "%FAMILY1:NOT_DEF%_%TASK%"
      tmpdir_size: 20Gb
    sequential:
      total_tasks: 1